[package]
org = "nishal"
name = "backend"
version = "0.1.0"
distribution = "2201.12.6"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "mysql"
version = "1.10.0"